In [15]:
#Name: Ayesha Tariq
#Registration Number: SP20-BCS-020
#Group: 4

In [4]:
import pandas as pd
import numpy as np
from numpy.linalg import norm
from numpy.linalg import norm
import collections
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
data = ['sunshine state enjoy sunshine',
          'brown fox jump high , brown fox run',
          'sunshine state fox run fast' ]

In [5]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(data)
print(vectorizer.get_feature_names())

['brown', 'enjoy', 'fast', 'fox', 'high', 'jump', 'run', 'state', 'sunshine']


In [6]:
#Writing all documents in Vector form
print(X.toarray())

[[0 1 0 0 0 0 0 1 2]
 [2 0 0 2 1 1 1 0 0]
 [0 0 1 1 0 0 1 1 1]]


In [7]:
words_set = set()

for doc in  data:
    words = doc.split(' ')
    words_set = words_set.union(set(words))
    
print('Number of tokens in the data:',len(words_set))
print('The tokens in the data: \n', words_set)

Number of tokens in the data: 10
The tokens in the data: 
 {'high', 'jump', 'state', 'fast', 'brown', 'sunshine', 'run', ',', 'enjoy', 'fox'}


In [8]:
#Number of documents in the data
n_docs = len(data)    
#Number of unique words in the data     
n_words_set = len(words_set) 

df_tf = pd.DataFrame(np.zeros((n_docs, n_words_set)), columns=words_set)

#Term Frequency (TF)
for i in range(n_docs):
    words = data[i].split(' ') 
    for w in words:
        df_tf[w][i] = df_tf[w][i] + (1 / len(words))
        
df_tf

high   jump  state  fast  brown  sunshine    run      ,  enjoy   fox
0  0.000  0.000   0.25   0.0   0.00       0.5  0.000  0.000   0.25  0.00
1  0.125  0.125   0.00   0.0   0.25       0.0  0.125  0.125   0.00  0.25
2  0.000  0.000   0.20   0.2   0.00       0.2  0.200  0.000   0.00  0.20

In [10]:
print("IDF of: ")

idf = {}

for w in words_set:
    k = 0    # number of documents in the corpus that contain this word
    
    for i in range(n_docs):
        if w in data[i].split():
            k += 1
            
    idf[w] =  np.log10(n_docs / k)
    
    print(f'{w:>15}: {idf[w]:>10}' )

IDF of: 
           high: 0.47712125471966244
           jump: 0.47712125471966244
          state: 0.17609125905568124
           fast: 0.47712125471966244
          brown: 0.47712125471966244
       sunshine: 0.17609125905568124
            run: 0.17609125905568124
              ,: 0.47712125471966244
          enjoy: 0.47712125471966244
            fox: 0.17609125905568124


In [11]:
df_tf_idf = df_tf.copy()

for w in words_set:
    for i in range(n_docs):
        df_tf_idf[w][i] = df_tf[w][i] * idf[w]
        
df_tf_idf

high     jump     state      fast    brown  sunshine       run        ,  \
0  0.00000  0.00000  0.044023  0.000000  0.00000  0.088046  0.000000  0.00000   
1  0.05964  0.05964  0.000000  0.000000  0.11928  0.000000  0.022011  0.05964   
2  0.00000  0.00000  0.035218  0.095424  0.00000  0.035218  0.035218  0.00000   

     enjoy       fox  
0  0.11928  0.000000  
1  0.00000  0.044023  
2  0.00000  0.035218

In [12]:
#Cosine Similarity
C_S1 = np.array([2, 0, 0, 0, 1, 0, 0, 0, 1])
C_S3 = np.array([1, 1, 1, 0, 0, 1, 0, 0, 1])

In [13]:
cosine = np.dot(C_S1,C_S3)/(norm(C_S1)*norm(C_S3))
print("Cosine Similarity of S1 and S3 is = ", cosine)

Cosine Similarity of S1 and S3 is =  0.5477225575051661
